baseURL = 'https://blog.rinogodson.com/'
languageCode = 'en-us'
title = ''
theme = 'PaperMod'

[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = "Blog Posts"
    Content = ""
